### PR TITLE
Adding Switch connection view for dell 14g servers

### PR DESCRIPTION
**Pull request by keedya**
depends on: 
- https://github.com/RackHD/smi-lib-wsman/pull/17

### CODE REVIEW

**Comment by keedya** [comment]
tagging @michaelsteven @phelpdh  for reviews

**Review by michaelsteven — APPROVED** [review]
looks fine

**Comment by michaelsteven** [comment]
@keedya Please change build.gradle dependencies to use the newly built com.dell.isg.smi:wsmanlib:1.0.67

**Comment by keedya** [comment]
@michaelsteven all set!!

**Review by phelpdh — APPROVED** [review]
All good

**Pull request merged**
